In [1]:
import numpy as np

In [9]:
array=np.arange(10)                               convert 1d array to a 2d array with 2 rows
array.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array1=np.array([[0,1,2,3,4],[5,6,7,8,9]])        how to stack two arrays vertically
array2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((array1,array2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
array1=np.array([[0,1,2,3,4],[5,6,7,8,9]])         how to stack two arra horizontally
array2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((array1,array2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [20]:
array1=np.array([[0,1,2,3,4],[5,6,7,8,9]])          how to convert an array of arrays into a flat 1d array
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
array1=np.array([[[0,1,2,3,4],[5,6,7,8,9]]])        how to convert higher dimension into one dimension
array1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr=np.arange(25).reshape(5,5)                     create 5 by 5 an array and find the square of an array
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [49]:
array=np.arange(30).reshape(5,6)                  create 5 by 6 an array and find the mean  
np.mean(array)

14.5

In [50]:
arr=np.arange(30).reshape(5,6)                      find the standard deviation of the previous array 
np.std(arr)

8.65544144839919

In [51]:
array=np.arange(30).reshape(5,6)                   
np.median(array)                                     find the median of the previous array


14.5

In [43]:
array=np.arange(30).reshape(5,6)                     find the transpose of the previous array 
np.transpose(array)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [53]:
array=np.arange(16).reshape(4,4)                     create a 4 by 4 an array and find the sum of diagonal elements
np.trace(array)

30

In [57]:
array=np.arange(16).reshape(4,4) 
np.linalg.det(array)                                find the determinant of the previous array

-2.9582283945787796e-30

In [59]:
arr=np.arange(100).reshape(10,10)                   find the 5th and 95th percentile
np.percentile(arr,95)                                95th percentile

94.05

In [60]:
np.percentile(arr,5)                                   5th percentile


4.95